language: java
jdk:
  - oraclejdk8

env:
  global:
    - secure: "sMZqSvsLTvhkxq6BQuwkQ9BJmuOeejDNDYyHI1DPVFwXHRo7/qOc0BSHoGfxgUUjiLkm+TJllMv8CqXcPwzVk6OfUAMJn5lQkFheo8wRyOyrpc+4grVWGm43v7tEVijG08LxzHdF3vrswSzCwwTgxtWZw/seuaPVBn1DmqbrJjJkXNjYs1Lo2ShlwuGkl1r8dHjG/+6o0uwduwL2wJHcsb7T07K/dwPmoDEDNL0eCJnM2g51n8zwnzVateb+hTuCGMzCv6PjSnEqGo9Y/F76C5G9zFZWSNX2sw4Uvi4a2JkwXWLJy0y33lEyb5asa4OY25dAmjxJoF7nU8uyEe5XvH5L2tExg4Npi3GvzWO2bFhdT1lI192NY9FeFt4eb6RgD9kYS6fjLtfBWNFDRRZ6OrNpNpgF2DDiKFp5uV4yKeDlmgfJVmXieSjYlF7Ts41j5OxgS9fSAA7TW6jLare2a5o3B8ZZZW0BSGzXBM7Kybuko2bcIkFTqa5i9lD3pFERxVYnL0xv/Fx1SkWR4O4VOJ8Lgu3Qq0OEYYWXSvGApk7otUISaRULMYuG+ksqnDzZVQB/kwPspxcoSFFoPSulaf50AW0K7/9r16r2u2yx+QRm2+1dL8BMiObTaVjglxRfT8+Zy58h3zMkB4a1dF3k+hdE58WQAY8QpSdA5Yr4j9k="
    - # ^^ OSSRH_JIRA_USERNAME
    - secure: "VyojJZP6RaEK+v6jqQ04Fi9BaLUYF6yxfAZ4ZQWlZOwl+plJXcTOEj0yhNVnosg8OniBd373L8v5eVrcjSPkKhHzlv4Q0KuJw55PS6Q0mDt8MucjymI5lFfw9VJJhqZBLpT5iz4nxndNwKc8Xf7QTAAhUtqQdtVPfIM/wIeD7Ic0vin1AidjBPChpPQVM7OPV/0yfe5S6IwYd48/pqF88BeBnlvzUUEdpswosh8x/l1NrqPkHmBmvs4kq8FoFVOl+2lEboBdUT85ggBruV/g89MKzwbiE8NwlY/Wv9ZJHtqsAEg330BW1dQ1x059r5QOu1aV9rx1f9s6MeUoC3+FYDzi/f7RfPpkTvPd/hBA3NRJ4EHyika7sn/24+s/3PGhmByTD2bTkYT5QwyQVckjNKMcpndELTGlgeBeBHrmpT8fi3Q6DaPfmTdFq1XGN/xPaJxAlsRkFfVU+uRa38znRX1mlKIvWLYwSd6/s/hlCfs6aAa2XjHMtXeViRKvfqTMImMVh2dkPMK62rx+h0YTxxFWMmzPGq9xkkQauimgQMUK1UB61YHXG9uJ1zxp7D4BNU4pVl7aswcB/+hfm9IXpF/u+pk2tW6eVQaCbtg0ERUptsK+IQPhcTDnATxdvZIfQYuvwj5T17Smtfj8YaEFQKS4wrTr1g+Ei6r7DryskKI="
    - # ^^ OSSRH_JIRA_PASSWORD
    - secure: "RvOLFRJgHKN9En4JyxDPQILxEJlhCSuFHS/HTvkvvVrgp7haR4ADXW3ThoSiWwk07bBH8oEgsgskyEaufwrc/FmONoLwa1y9kjObhLqzlrCSqdcUaZ/3lhFCm3SX3/d9dd1OjG3Ov2SlopktyFB84DJq8wQshyKbVU/pnn2Y/nkiwngsx2VKVwxEe6D3Vu84ZIqjhEC2dqdjfz46Qa4Bq+2Ak3NPbNBnyw2jendjhgmhrCdl9hk6StiNT4NAHlAob+2XoBQDsL/kdq4Hk59rRmO6aD2m62ggnqvHYsZxjatmXsIlhCmH1+U5OycweUPCuMuyJdbel1qV5AX2NhVY+OHny+ox3nz/kpoknHylUf5bzF0QR+gCoEF97fnp92XHGffgo/spbvY2BAxw7x9B5kw86uFdSV0YSKh7w5TAe/Rr8Sg8Rplj67l4ifTDajVAl6IHLPKQcdu1xfqS3H3qvnOpQS1NmJPj8MoteralOQyucZXSYOdmTgAkp60ihJZ0zzbvQJ1bvZr7bR4fEGKsDBu9UTSSmvxlZewXE1O4OK3dE5q3UHXTOahw5LJTSs+tF4jXI31Cwdi27F5Pi402NndFirKLSzox4HmwWKCrXbf1ejVBFzweOp4sOuQ8pmfd5eYS1fsWacD9DXg2G/z1nTt4mDq/MW6Lsg42aQcoUSY="
    - # ^^ GPG_KEY_NAME
    - secure: "K6G6iK2dNBL25E1op2Nn/SiapIWnyp5jDtTjEVbRT6GqqBcGJAaNMM0VX4OmEA7jYDAXVF3nuxrPCgrxPFrXsm2igkHl5B/13EyuongZ64gsx5AKquD54DgaRLiHVNHW2m3MRbl244/8njRHqHilslNiVKbzB0ViM+c5hZ0vXBDz+2iRiSNE5KHRSqtSYx8DDQVqqpBlbJl5nSr8djOoGgso7yXX7Tl+tmfxqBX0AcrUNIhqOMhZvN6g/0o/WRcB9U0tltObOHwkwlitApGO4aRWmXGrzNLf2piXDzc8lLZ72TI9rVcUp6E7+yNA/MsT3Elt/i+hUzCMsO8XNVOjt+P7W6Wtjgpr2wjN4MApmmeH6ptid3i5s6v77HeWg1sL0HCblIzFkMUsVhT6JXFeQDhIevyKrXXnTos+ZVoUKcVO5uIScJrcbEI5TSbztLeumSPTepyL+oSmUQg1BnxdIsMYhPT+AqrNORPGD72YhMUDiDL/Ac96Ed2NMjCt/MFyfPvvhbT3aXt/HwnatfkgzR/+eV5nXcSCapt4aakO20EwC2iZR5cvyYoexCF1/vxtq1mB/NkPGZephjJJf06JohStPyHtfsgyAtpogLWI5JfUyrhecSZ7OkplOiUhQ4/S8aqtYWP+pKl3shGbBKgEcUucZQs7s7ioJM6kZ52CFww="
    - # ^^ GPG_PASSPHRASE

sudo: required
services:
  - docker

install: ./mvnw install -P !build-extras -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./mvnw -B -P !build-extras test

deploy:
  sudo: false
  services: []
  provider: script
  script: release/deploy.sh
  on:
    tags: true
    branch: master

cache:
  directories:
    - '$HOME/.m2/repository'
